### ISSUE TITLE
make test very slow on Windows

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#2095]
During investigation of #2092 it was found that "make test" runs about 5x slower on the Github action builds for Windows than Linux. I'm not sure of the cause.

It could be that the MSVC builds are really that much slower, in which case I think there must be some incorrect compiler settings, as there really should not be a 5x speedup between this and MinGW GCC.

The other stronger suspicion I have is that **"make" is somehow much slower on the Windows platform**. If that's the case I'm not sure if there's much we can do about it, unless there's something problematic about the way our particular makefiles are written that is an issue for Windows only.

Either way, it would be nice to understand it, and even nicer to fix it.

Edit: for quick reference I've made the correct answer **bold** above. (The binaries are fine, make is the problem.)

**Comment by mrdudz** [comment]
> The other stronger suspicion I have is that "make" is somehow much slower on the Windows platform. 

That is the case. Windows is awfully slow at spawning processes (which happens a lot during make). I don't think there is a way to fix this. VICE builds really really slow on Windows for that matter (for the same reasons).

That said, the build environment doesn't seem to ever truly use a native windows shell - at least not for the subshells used by "make". see #1920 and #1937 for that matter

**Comment by bbbradsmith** [comment]
So I made a test on my fork, building and testing both MSVC and GCC in the same job (just to be sure it's the same machine at least), and then another job in the reverse order. The time differences are not significant between the two, so I think that at least puts to rest the idea that the MSVC is horribly misconfigured. Details follow, if curious:

# Details

Starting from #2092 which fixes sim65 so that the MSVC test can pass.

I created [a workflow](https://github.com/bbbradsmith/cc65/blob/0749a59968af620b29f439b8d43fd30b46399702/.github/workflows/windows-performance-test.yml) that looked like this:
```
name: Windows Performance Test
on: [pull_request]

jobs:

  build_msvc_gcc:
    name: Build MSVC then GCC
    runs-on: windows-latest

    steps:
      - name: Git Configure
        shell: bash
        run: git config --global core.autocrlf input
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: MSVC Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: MSVC Build app (release)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Release
      - name: MSVC make lib
        run: make -j2 lib QUIET=1
      - name: MSVC make test
        run: make test QUIET=1

      - name: Blank Slate
        shell: bash
        run: ls -A1 | xargs rm -rf
      - name: Git Configure
        shell: bash
        run: git config --global core.autocrlf input
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: MinGW Build app
        run: make -j2 bin USER_CFLAGS=-Werror
      - name: MinGW make lib
        run: make -j2 lib QUIET=1
      - name: MinGW make test
        run: make test QUIET=1

  build_gcc_msvc:
    name: Build GCC then MSVC
    runs-on: windows-latest

    steps:
      - name: Git Configure
        shell: bash
        run: git config --global core.autocrlf input

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: MinGW Build app
        run: make -j2 bin USER_CFLAGS=-Werror
      - name: MinGW make lib
        run: make -j2 lib QUIET=1
      - name: MinGW make test
        run: make test QUIET=1

      - name: Blank Slate
        shell: bash
        run: ls -A1 | xargs rm -rf
      - name: Git Configure
        shell: bash
        run: git config --global core.autocrlf input
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: MSVC Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: MSVC Build app (release)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Release
      - name: MSVC make lib
        run: make -j2 lib QUIET=1
      - name: MSVC make test
        run: make test QUIET=1
```

The [timing results](https://github.com/bbbradsmith/cc65/actions/runs/4896224581):
```
Build MSVC then GCC
 00:01 - Set up job
 00:00 - Git Configure
 00:07 - Checkout Source
 00:01 - MSVC Add msbuild to PATH
 01:44 - MSVC Build app (release)
 01:54 - MSVC make lib
 27:14 - MSVC make test
 00:05 - Blank Slate
 00:00 - Git Configure
 00:03 - Checkout Source
 00:44 - MinGW Build app
 01:28 - MinGW make lib
 24:19 - MinGW make test
 00:01 - Post Checkout Source
 00:01 - Post Checkout Source
 00:00 - Complete job
 --------------------
 57:47 - Total


Build GCC then MSVC
 00:01 - Set up job
 00:02 - Git Configure
 00:07 - Checkout Source
 01:09 - MinGW Build app
 01:56 - MinGW make lib
 30:07 - MinGW make test
 00:06 - Blank Slate
 00:00 - Git Configure
 00:04 - Checkout Source
 00:01 - MSVC Add msbuild to PATH
 01:24 - MSVC Build app (release)
 02:17 - MSVC make lib
 29:32 - MSVC make test
 00:01 - Post Checkout Source
 00:01 - Post Checkout Source
 00:00 - Complete job
 --------------------
 60:06 - Total
 ```
