### ISSUE TITLE
scheduled Windows build test

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#2106]
#2101 added an action that an administrator can manually trigger to test the windows build. It was not added to the snapshot/PR workflows because of how slow it is (#2095), i.e. adds about 25 minutes to the test, which is otherwise only about 5m total.

[A scheduled version was requested](https://github.com/cc65/cc65/pull/2101#issuecomment-1537379780) but because I could not figure out a sensible way to control notifications from it.

This is different from 

* Also runs on a cron schedule.
* Create a cache storing the last used SHA so that it doesn't re-run the tests on no changes.
* Add an `if` to each build step to skip on no change.

Unlike push triggered actions, the notification seems to go to the person who created the action instead? Not exactly sure what the notification assignment is, but the lack of clarity in documentation and my own tests made me hesitant to create a PR that does it. I didn't want to have it generating e-mails all the time to myself or someone else who doesn't want then, and I couldn't see a way to properly/easily designate that.

Another downside of this caching approach is that after it fails once, if the cause isn't fixed before the next cron, the action will pass because it skips everything when the last one was successful. There's probably an easy solution to this... maybe deleting the cache on failure? I hadn't worked out how to do this.

The cron is set to every 5 days here. It seems that caches only last a maximum of 7 days normally, so it should at least be less than that.

```
name: Windows Test Schedule

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:
    # Allow manual dispatch.

jobs:
  build_windows:
    name: Build, Test (Windows MSVC)
    runs-on: windows-latest

    steps:
      - name: Setup
        shell: bash
        run: |
          git config --global core.autocrlf input
          mkdir cache-sha

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Cache SHA
        uses: actions/cache@v3
        id: cache-sha
        with:
          path: cache-sha
          key: cache-sha-${{ github.sha }}

      - name: Build app (MSVC debug)
        if: steps.check-sha.outputs.cache-hit != 'true'
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Debug

      - name: Build app (MSVC release)
        if: steps.check-sha.outputs.cache-hit != 'true'
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Release

      - name: Build utils (MinGW)
        if: steps.check-sha.outputs.cache-hit != 'true'
        shell: cmd
        run: make -j2 util

      - name: Build the platform libraries (make lib)
        if: steps.check-sha.outputs.cache-hit != 'true'
        shell: cmd
        run: make -j2 lib QUIET=1

      - name: Run the regression tests (make test)
        if: steps.check-sha.outputs.cache-hit != 'true'
        shell: cmd
        run: make test QUIET=1

      - name: Test that the samples can be built (make samples)
        if: steps.check-sha.outputs.cache-hit != 'true'
        shell: cmd
        run: make -j2 samples
```
